### ISSUE TITLE
Covariant mode may traceback

### ISSUE THREAD

**Issue by ether42** [RussBaz/enforce#39] opened 2017-05-25 21:01 UTC
Version used:
```shell
pip show enforce
Name: enforce
Version: 0.3.3
...
```

Simplest reproducible example:
```python
from typing import Optional
from enforce import config, runtime_validation

config({'mode': 'covariant'})

@runtime_validation
def example() -> Optional[str]:
    return None

example()
```
Note that if I comment out the `config` call, it works as expected.
Of course, the covariant mode isn't useful here, but I do need it in a larger script.

The traceback itself, for completeness:
```
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    example()
  File ".../venv/lib/python3.6/site-packages/enforce/decorators.py", line 118, in universal
    return enforcer.validate_outputs(result)
  File ".../venv/lib/python3.6/site-packages/enforce/enforcers.py", line 96, in validate_outputs
    if not self.validator.validate(output_data, 'return'):
  File ".../venv/lib/python3.6/site-packages/enforce/validator.py", line 26, in validate
    validation_result = visit(validation_tree)
  File ".../venv/lib/python3.6/site-packages/enforce/utils.py", line 17, in visit
    stack.append(last.send(last_result))
  File ".../venv/lib/python3.6/site-packages/enforce/nodes.py", line 54, in validate
    self_validation_result = self.validate_data(validator, clean_data, force)
  File ".../venv/lib/python3.6/site-packages/enforce/nodes.py", line 210, in validate_data
    result = is_type_of_type(input_type, expected_data_type, covariant=covariant, contravariant=contravariant)
  File ".../venv/lib/python3.6/site-packages/enforce/types.py", line 206, in is_type_of_type
    subclass_check = perform_subclasscheck(data, data_type, covariant, contravariant)
  File ".../venv/lib/python3.6/site-packages/enforce/types.py", line 234, in perform_subclasscheck
    result = result or data_type.__subclasscheck__(reversed_data)
TypeError: issubclass() arg 1 must be a class
```

**Comment by RussBaz** [comment] 2017-05-27 17:03
Interesting. I will have a look this week. Thanks for reporting.

**Comment by RussBaz** [comment] 2017-05-29 17:55
This issue is now supposed to be fixed in the Dev branch. Please try it if you can. I will wait before publishing an update to PyPi in case there are still some problems with a patch.

Please report if it now works for you workload.

Thank you.

**Comment by ether42** [comment] 2017-05-29 18:15
Your patch seems ok, I had only two use cases which mainly depended on `Optional`/`Union`:
 - return type `Optional[a]`
 - parameter type `List[Optional[b]]`

So as I thought it was the special handling of `None` instead of `NoneType` but I don't know if there is a cleaner way to handle this peculiarity than what you've done.

Thanks.

**Comment by RussBaz** [comment] 2017-05-30 04:12
I will think about it. I am closing an issues for now as it seems to be working as intended. I will reopen it if there are some other misbehaving corner cases discovered.

**Closed by RussBaz** 2017-05-30 04:12 UTC
